### ISSUE TITLE
How to use ArrayList

### ISSUE THREAD

**Issue by tcqq** [liip/viewmodel-savedstate-helpers#12]
```
class RegionsViewModel(handle: SavedStateHandle): ViewModel() {
    var selectedPositions by handle.delegate<ArrayList<Int>>()
}
```

When I call this code: 

`viewModel.selectedPositions.contains(position)`

selectedPositions is empty, how should I fix it? @jschmid

**Comment by jschmid** [comment]
First, you have to initialize the `ArrayList`. The delegate does not do it for you. Something like:


```kotlin
var selectedPositions by handle.delegate<ArrayList<Int>>()

init {
    if(selectedPositions == null) {
        selectedPositions = ArrayList()
    }
}
```

Second, you **cannot** use a mutable object like `ArrayList` like that.
The way the _delegate_ works means that you always have to **set** a value to your delegated property. You can mutate/change it.

If you wanted to change the list and still save it using the delegated property, you would have to do something like:

```kotlin
val array = selectedPositions
array?.add(Random.nextInt())
selectedPositions = array
```

**Comment by tcqq** [comment]
Thanks i understand.
