### ISSUE TITLE
Unresolved reference: SavedStateVMFactory

### ISSUE THREAD

**Issue by AlexanderBykin** [liip/viewmodel-savedstate-helpers#3]
Hi.

This error happens when i try to compile your `demo` project by myself.
What can be wrong?
```
viewmodel-savedstate-helpers\demo\src\main\java\ch\liip\viewmodelsavedstatehelpers\demo\MainActivity.kt: (6, 27): Unresolved reference: SavedStateVMFactory
```

**Comment by jschmid** [comment]
Hi @AlexanderShniperson,

I just did a fresh clone from `master`. On my side, it works with Android Studio 3.4.1 and using the command line with `./gradlew assemble` from the root folder.

Can you tell me more from where you get the error ?

**Comment by jschmid** [comment]
Did you update the library from `alpha01` to `alpha02` in the demo?

**Comment by AlexanderBykin** [comment]
@jschmid 
yes i'm upgraded library in `demo` and it looks like it is related to version `alpha02`
rolled it back to `alpha01` and compilation went success
thanks

**Comment by jschmid** [comment]
Thanks for the update. 

I will update the versions with alpha02 soon.

**Comment by jschmid** [comment]
The demo is updated. You can now use the alpha02 version!

```groovy
    implementation 'com.github.liip:viewmodel-savedstate-helpers:1.0.0-alpha02'
```
